// "use client";
import type { Metadata } from "next";
import "@/app/ui/global.css";
import "@/app/ui/satoshi.css";
import { inter } from "@/app/ui/fonts";
import Template from "./ui/layout/template";
// import Sidebar from "./ui/layout/sidebar/sidebar";
// import Header from "./ui/layout/header/header";
// import { useState } from "react";

export const metadata: Metadata = {
  title: "Tsubasa Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  // const [sidebarOpen, setSidebarOpen] = useState(false);

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="dark:bg-boxdark-2 dark:text-bodydark">


          <Template> {children}</Template>
          




        </div>
      </body>
    </html>
  );
}
